Parameters:
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: must be a valid EC2 instance type.
  SubnetId:
    Description: Select the Subnet where the VM should be deployed
    Type: String
    ConstraintDescription: Must be a valid subnet
  ImageId:
    Description: Select the Image to deploy
    Type: String
    ConstraintDescription: Must be a valid ImageId

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2c
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
