Parameters:
  Name: 
    Description: Name for the EC2 Instance
    Type: String
    AllowedPattern: ^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: must be a valid EC2 instance type.
  SubnetId:
    Description: Select the Subnet where the VM should be deployed
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: Must be a valid subnet located in the selected AZ
  ImageId:
    Description: Select the Image to deploy
    Type: AWS::EC2::Image::Id
    ConstraintDescription: Must be a valid ImageId
  KeyPair:
    Description: Select the key pair
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be a valid AWS Key Pair
  

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      KeyName: !Ref KeyPair
      Tags:
        - Key: Name
          Value: !Ref Name

Outputs:
  PrivateIp:
    Description: Private IP address of the EC2 Instance
    Value: !GetAtt MyInstance.PrivateIp
  PrivateDnsName:
    Description: Private DNS Name of the EC2 Instance
    Value: !GetAtt MyInstance.PrivateDnsName
  