Parameters:
  InstanceType:
    Description: WebServer EC2 instance type (has default, AllowedValues)
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: must be a valid EC2 instance type.
  SubnetId:
    Description: Select the Subnet where the VM should be deployed
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: Must be a valid subnet located in the selected AZ
  ImageId:
    Description: Select the Image to deploy
    Type: AWS::EC2::Image::Id
    ConstraintDescription: Must be a valid ImageId

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId

Outputs:
  PrivateIp:
    Description: Private IP address of the EC2 Instance
    Value: !GetAtt MyInstance.PrivateIp
  PrivateDnsName:
    Description: Private DNS Name of the EC2 Instance
    Value: !GetAtt MyInstance.PrivateDnsName
  PublicDnsName:
    Description: Public DNS Name of the EC2 Instance
    Value: !GetAtt MyInstance.PublicDnsName
  PublicIp:
    Description: Public IP Address of the EC2 Instance
    Value: !GetAtt MyInstance.PublicIp
  